#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/common.sh"

ask() {
  local prompt="$1"
  local default_value="$2"
  local value

  if [[ -n "${default_value}" ]]; then
    read -r -p "${prompt} [${default_value}]: " value
    printf '%s' "${value:-${default_value}}"
  else
    read -r -p "${prompt}: " value
    printf '%s' "${value}"
  fi
}

ask_secret() {
  local prompt="$1"
  local value
  read -r -s -p "${prompt}: " value
  printf '\n' >&2
  printf '%s' "${value}"
}

sq_escape() {
  local value="$1"
  printf "%s" "${value}" | sed "s/'/'\\''/g"
}

main() {
  require_root

  log "INFO" "Interactive setup for /etc/backup-restore.env"

  local restic_repository
  local restic_password
  local backup_root
  local stack_config_paths
  local portainer_url
  local portainer_username
  local portainer_password
  local portainer_endpoint_id
  local restic_forget_args
  local restic_sftp_password
  local restic_sftp_command
  local slack_webhook_url
  local slack_notify_channel
  local restore_target
  local restic_snapshot
  local restic_host

  restic_repository="$(ask "RESTIC_REPOSITORY" "")"
  if [[ -z "${restic_repository}" ]]; then
    fail "RESTIC_REPOSITORY is required."
  fi

  restic_password="$(ask_secret "RESTIC_PASSWORD")"
  if [[ -z "${restic_password}" ]]; then
    fail "RESTIC_PASSWORD is required."
  fi

  backup_root="$(ask "BACKUP_ROOT" "/opt/backup-restore")"
  stack_config_paths="$(ask "STACK_CONFIG_PATHS" "/opt/stacks:/srv/stacks:/etc/docker/stacks")"
  portainer_url="$(ask "PORTAINER_URL (optional)" "http://127.0.0.1:9000")"
  portainer_username="$(ask "PORTAINER_USERNAME (optional)" "")"
  portainer_password="$(ask_secret "PORTAINER_PASSWORD (optional)")"
  portainer_endpoint_id="$(ask "PORTAINER_ENDPOINT_ID (optional)" "1")"
  restic_forget_args="$(ask "RESTIC_FORGET_ARGS" "--keep-daily 7 --keep-weekly 4 --keep-monthly 6 --prune")"
  restic_sftp_password="$(ask_secret "RESTIC_SFTP_PASSWORD (optional, for SFTP password auth)")"
  restic_sftp_command="$(ask "RESTIC_SFTP_COMMAND (optional custom restic sftp.command)" "")"
  slack_webhook_url="$(ask "SLACK_WEBHOOK_URL (optional)" "")"
  slack_notify_channel="$(ask "SLACK_NOTIFY_CHANNEL (optional)" "")"
  restore_target="$(ask "RESTORE_TARGET" "/restore-output")"
  restic_snapshot="$(ask "RESTIC_SNAPSHOT" "latest")"
  restic_host="$(ask "RESTIC_HOST (optional)" "")"

  install -m 600 /dev/null /etc/backup-restore.env

  cat > /etc/backup-restore.env <<EOF
# Generated by scripts/setup-env.sh
# This file is loaded by systemd via EnvironmentFile=/etc/backup-restore.env

RESTIC_REPOSITORY='$(sq_escape "${restic_repository}")'
RESTIC_PASSWORD='$(sq_escape "${restic_password}")'
BACKUP_ROOT='$(sq_escape "${backup_root}")'
STACK_CONFIG_PATHS='$(sq_escape "${stack_config_paths}")'
PORTAINER_URL='$(sq_escape "${portainer_url}")'
PORTAINER_USERNAME='$(sq_escape "${portainer_username}")'
PORTAINER_PASSWORD='$(sq_escape "${portainer_password}")'
PORTAINER_ENDPOINT_ID='$(sq_escape "${portainer_endpoint_id}")'
RESTIC_FORGET_ARGS='$(sq_escape "${restic_forget_args}")'
RESTIC_SFTP_PASSWORD='$(sq_escape "${restic_sftp_password}")'
RESTIC_SFTP_COMMAND='$(sq_escape "${restic_sftp_command}")'
SLACK_WEBHOOK_URL='$(sq_escape "${slack_webhook_url}")'
SLACK_NOTIFY_CHANNEL='$(sq_escape "${slack_notify_channel}")'
RESTORE_TARGET='$(sq_escape "${restore_target}")'
RESTIC_SNAPSHOT='$(sq_escape "${restic_snapshot}")'
RESTIC_HOST='$(sq_escape "${restic_host}")'
EOF

  chmod 600 /etc/backup-restore.env

  log "INFO" "Saved runtime configuration to /etc/backup-restore.env (mode 600)."
  log "INFO" "systemd services will load this file after reboot via EnvironmentFile=."
}

main "$@"
